### ISSUE TITLE
能够支持变量的名字显示吗？

### ISSUE THREAD

**Issue by sesefadou123** [hallee9000/heron-handoff#79]
我们设计了一套 token 变量，比如颜色的 token 名字叫xxxxxx，现在导出后只能显示他们的硬值，却不能显示变量名字，这样交付给开发无法查看用调用了那个 token 值

**Comment by istraw** [comment]
我也是来求这个功能的，目前用变量设计会遇到无法查看变量命名的问题

**Comment by hallee9000** [comment]
你好，这个插件目前处于维护状态，没有更新计划了，可以考虑使用[月维](https://moonvy.com/?homepage)。
